### ISSUE TITLE
1c Innovation Short Name

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#1]
Max 8 word limit not enforced. 

Add "You have exceeded the limit of eight (8) words"

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed! please check and let me know!

**Comment by marcusschut** [comment]
Doesn't give me "You have exceeded the limit of eight (8) words"

**Comment by marcusschut** [comment]
Should be 8 words (not 8 characters)

"You have exceeded the limit of eight (8) words"
![Uploading Screenshot 2021-05-27 at 08.39.03.png…]()

**Comment by sotkonstantinidis** [comment]
fixed
