### ISSUE TITLE
i can't edit the innovations

### ISSUE THREAD

**Issue by ibaltenweck** [icarda/Online-Innovation-Inventory-From#13]
hello- i can't edit the innovations and therefore can't finalise. Maybe I'm missing where? thanks

**Comment by sotkonstantinidis** [comment]
hi @ibaltenweck ! The edit has been just finalized & enabled. You can edit your stored innovations by pressing the edit button (the blue one) from the "My Innovations" space. 

If you spot any bug through the process please let us know!
