### ISSUE TITLE
Saving??

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#16]
Dear colleagues,

Apart from the glitch reported below, I logout and log in again and the innovation I was working on was not saved. This is actually another problem of the tool because when I was entering the innovation information, I went till the last step and saved.

Please solve these technical problems or alternately allow IDTs to submit the information in the Excel template

Kind regards,

Marcela

**Comment by sotkonstantinidis** [comment]
@marcusschut The saving seems to work, we need more details to re-crate the problem. It would help if we could have the actual path that the user has been taken.

**Comment by marcusschut** [comment]
Seems to work indeed now
