### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#18]
I completed the survey and filled all mandatory fields, yet when I save it tells me that I did not fill all fields and my innovation has status "Draft".

Can you check?

**Comment by sotkonstantinidis** [comment]
@marcusschut I have setted all the fields as mandatory (with exeption of the history since it has a default value). To my understanding the only step/field that is not mandatory is the reference material? If this is the case, I can make the update immediately

**Comment by marcusschut** [comment]
Correct, the only field that is not mandatory is the reference material

**Comment by sotkonstantinidis** [comment]
@marcusschut will make the update in few minutes

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed! Added an innovation without refs and it's status has been resolved as "FINAL". As usual please check and let me know :)
