### ISSUE TITLE
Not being able to "Save" reference materials.

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#19]
I provide URL and try to save, but it does not allow me and I can only "Cancel" <img width="844" alt="Screenshot 2021-06-03 at 22 44 11" src="https://user-images.githubusercontent.com/47771774/120709512-3b702380-c4bd-11eb-8667-fbf5477d1201.png">

**Comment by sotkonstantinidis** [comment]
@marcusschut from my side it seems to work, could you please try again? If the problem persists the we should probably make a telco tomorrow to re-create the issue

**Comment by marcusschut** [comment]
Works!

**Comment by marcusschut** [comment]
Tested again, but facing the same issues as before... nothing happens when clicking Save. I uploaded innovation without reference materials, then saved, then edited and tried to add ref materials.

**Comment by sotkonstantinidis** [comment]
@marcusschut managed to re-create it and fixed
