### ISSUE TITLE
2c Initiative Outcomes

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#2]
If one goes back from Section 2c back into Section 1 and changes 1a Initiative Name then the Outcomes under 2c need to be updated to match the newly selected Initiative under 1a

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed, please check whenvever you can

**Comment by marcusschut** [comment]
I checked, but still bug: https://www.dropbox.com/s/uyvhm09o5kq1va2/Screenshot%202021-05-25%20at%2022.52.42%282%29.png?dl=0

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed

**Comment by marcusschut** [comment]
This problem has emerged again... I selected an Initiative A, then a selected a Outcome of Initiative A, then changed to Intiative B, then Outcomes of Initiative A still features in Section 2c, and not all Outcomes of Initiative B feature (only 3 out of 4 / 4 out of 5). Pls check.
