### ISSUE TITLE
CGIAR Innovation History - True/ False

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#20]
When selecting 'Yes' it autofills "True" could this be a bug? Also in the summary it displays "false" when selecting "No" here. <img width="787" alt="Screenshot 2021-06-03 at 22 46 26" src="https://user-images.githubusercontent.com/47771774/120709755-8b4eea80-c4bd-11eb-8c7d-b48168580d2b.png">

**Comment by sotkonstantinidis** [comment]
@marcusschut definetly a bug

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!

**Comment by marcusschut** [comment]
<img width="768" alt="Screenshot 2021-06-03 at 23 56 47" src="https://user-images.githubusercontent.com/47771774/120717170-5f386700-c4c7-11eb-911b-1910220936b2.png">
Still seems to have an issue... now saying 'no' when clicking yes->no->yes

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!
