### ISSUE TITLE
When expanding all fields in VIEW and REVIEW page there is no possibility to scroll down

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#22]
<img width="1440" alt="Screenshot 2021-06-03 at 23 02 57" src="https://user-images.githubusercontent.com/47771774/120711677-f4cff880-c4bf-11eb-8306-e4bbb77386a3.png">

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!
