### ISSUE TITLE
Tried to "Save" an innovation with 0 fields filled and got blank page

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#23]

**Comment by marcusschut** [comment]
@sotkonstantinidis - and now cannot access the system any more :-) Can you rescue me so I can keep testing/ reporting bugs :-)

**Comment by sotkonstantinidis** [comment]
@marcusschut give me minute and you will be back :)

**Comment by marcusschut** [comment]
Ok... I'll poor myself a drink :-)

**Comment by sotkonstantinidis** [comment]
@marcusschut ok, you should be fine now. The system could not "read" an empty innovation, but now is fixed! (please do not forget to ctrl+f5)

**Comment by marcusschut** [comment]
I'm back in!
