### ISSUE TITLE
3a Mapping to Work Packages

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#3]
If one goes back from Section 3a back into Section 1 and changes 1a Initiative Name then the Work Packages under 3a need to be updated to match the newly selected Initiative under 1a

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed, please check whenvever you can

**Comment by marcusschut** [comment]
Checked but still bug... I selected a WP, then changed the Initiative Name, and went back to 3a WP and earlier selected WP was still there: https://www.dropbox.com/s/xtpy5ymvig8x8xl/Screenshot%202021-05-25%20at%2022.52.56.png?dl=0

**Comment by marcusschut** [comment]
I could give a quick demo of the problem is that is useful.

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!

**Comment by marcusschut** [comment]
This problem has emerged again... I selected an Initiative A, then a selected a WP of Initiative A, then changed to Intiative B, then WP of Initiative A still features in Section 3a, and not all WPs of Initiative B feature (only 3 out of 4 or 4 out of 5)
