### ISSUE TITLE
'Next' button gives white screen (when not filling any data)

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#5]
When I click 'Next' in any of the Sections without filling any of the fields, I get a white screen. 'Previous' button seems to work properly

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed! Please check and let me know!

**Comment by marcusschut** [comment]
Still same issue, when randomly selecting fields and then clicking next

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!
