### ISSUE TITLE
System gives white screen when providing information

### ISSUE THREAD

**Issue by marcusschut** [icarda/Online-Innovation-Inventory-From#6]
When entering data, the system suddenly gives a white screen. It usually happens when clicking on one of the fields, or when clicking the 'Next' button. Refreshing does not recover the provided information.

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed! the edit functionality caused this issue. I removed the functionality. Please check that the typical workflow works and let me know

**Comment by sotkonstantinidis** [comment]
@marcusschut fixed!
